### ISSUE TITLE
'items+logic' option of JReduce getting an error about the class-hierarchy

### ISSUE THREAD

**Issue by akshayutture** [jdebloat/jdebloat#2]
The PLDI version (items+logic option) of the JReduce tool is giving a warning about not finding some classes.
Not sure if this really is an issue. Need to investigate more.

15:20:01 │ │ │ ├ Compute hierarchy
15:20:06 │ │ │ │ ├ Could not find: com/sun/source/util/TreePathScanner
15:20:06 │ │ │ │ ├ Could not find: org/apache/tools/ant/Task
15:20:06 │ │ │ │ ├ Could not find: com/sun/source/util/SimpleTreeVisitor
15:20:06 │ │ │ │ ├ Could not find: com/sun/source/util/SimpleTreeVisitor
15:20:06 │ │ │ │ ├ Could not find: com/sun/source/util/TreeScanner

**Comment by usama54321** [comment]
@akshayutture I am sorry for responding so late on this. Can you please confirm that both these issues are still open, as I see a recent commit to the repo. Thanks

**Comment by akshayutture** [comment]
Hi Usama! Thanks for offering to work on this issue, but I found out that this has to do with some recent changes to the JReduce tool, and I got help from Christian figuring this out. So I'm going to be making another commit soon which will hopefully fix this issue. I'll get back to you if I run into issues that I cannot fix.

The second issue is also still open, but I have a feeling that the commit I make will fix that too. I'll ping you if it doesn't.

**Comment by akshayutture** [comment]
> @akshayutture I am sorry for responding so late on this. Can you please confirm that both these issues are still open, as I see a recent commit to the repo. Thanks

Okay, actually the second issue (not this one) is something that I don't know how to fix. But I don't think we can do anything about the project's test-cases not passing. The only option, as I see it, is to drop those benchmarks.

**Comment by akshayutture** [comment]
It turns out that this issue had to do with benchmarks not building correctly. The faulty benchmarks were removed. There is no issue with Jreduce.
